version: "3.9"

services:
  valgrind-action:
    build:
      dockerfile: Dockerfile
      context: .
    image: valgrind-action
    container_name: valgrind-tester
    env_file:
      - .env
    volumes:
      - ./:/root/
